### DISCUSSION TITLE
How to make function names bold

### DISCUSSION THREAD

**Discussion by JerryI** [WLJSTeam/wljs-notebook#297] [Frontend & UI]
> a crosspost from Telegram support chat

Hey guys, would it be simple or hard to highlight functions names in bold ?

**Comment by JerryI** [comment]
we have interface only for colors, but luckily one can do this in principle (thanks to CodeMirror)


```css
  .ͼu {
    font-weight: 800;
}
```

just paste it as HTML cell, or directly to the settings (custom css)


![image](https://github.com/user-attachments/assets/e4b4b828-c216-4f85-8937-81452e0fce2d)


to alter the font, you can use this class

```css
.cm-line {
    font-family: ui-monospace !important;
}
```
